server:
  port: 18001
spring:
  application:
   ##name必须一样，不然高可用会导致unavailable-replicas
    name: guiyu-cloud-registeration
eureka:
  instance:
    hostname: guiyu-cloud-registeration1
  client:
    ##这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://guiyu-cloud-registeration2:18002/eureka/
      
#超时设置
ribbon:
  ReadTimeout: 30000 #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间
  MaxAutoRetries: 0   #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1  #切换实例的重试次数
  eureka:
    enabled: true