server:
  port: 18080
spring:
  application:
    name: guiyu-cloud-zuul
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18081/eureka/
      instance:
          status-page-url: http://localhost:18080/swagger-ui.html
##网关地址
#gateway:
#   host: http://guiyu-cloud-zuul:18080/
zuul:
  routes:
    guiyu-auth-web:
      path: /auth/**
      service-id: guiyu-auth-web
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false #禁用hystrix超时设置

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true