server:
  port: 18083
spring:
  application:
    name: guiyu-dispatch-web
#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
           defaultZone: http://47.96.151.197:18001/eureka/
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
  
properties:
  error: error.properties
        