server:
  port: 18083
spring:
  application:
    name: guiyu-dispatch-web
  # REDIS (RedisProperties)
  redis:
    database: 0
    host: 192.168.1.78
    password: 123456
    port: 6379  
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
  cache:
    type: redis
    cache-names: shiro.session,shiro.time 
#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
           defaultZone: http://192.168.1.78:18001/eureka/
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
  
properties:
  error: error.properties
 
jdbc_driver0: 
      com.mysql.jdbc.Driver
jdbc_url0: 
     jdbc:mysql://192.168.1.81:3306/guiyu_dispatch?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
jdbc_username0:
     root
jdbc_password0: 
     123456
validationQuery: 
     SELECT1
 
        