server:
  id: 1  #不同fsmanager需修改为不一样的，取值范围1至1023
  port: 19021

spring:
  application:
    name: guiyu-callcenter-fsmanager
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
jdbc_driver0: com.mysql.jdbc.Driver
jdbc_url0: jdbc:mysql://192.168.1.81:3306/guiyu_callcenter?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
jdbc_username0: callcenter
jdbc_password0: callcenter@1234
#jdbc_url0: jdbc:mysql://127.0.0.1:3306/guiyu_callcenter?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#jdbc_username0: root
#jdbc_password0: root
validationQuery: SELECT 1
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql

#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/

gateway:
  username: user
  password: pwd

properties:
  error: properties/error.properties

