server:
  port: 8081
properties:
  error: properties/error.properties
spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
