server:
  port: 18051
spring:
  application:
    name: guiyu-ai-web
  datasource:
    url: jdbc:mysql://47.97.179.12:3306/guiyu_ai
    username: root
    password: guiyu@1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/
properties:
  error: properties/error.properties
  threadpool: properties/threadPool.properties