server:
  port: 18051

spring:
  application:
    name: guiyu-ai-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.81:3306/guiyu_ai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true
    username: ai
    password: ai@1234
  redis:
    database: 8
    host: 192.168.1.81
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
    
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql

#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/

#网关地址
gateway:
  host: http://guiyu-cloud-zuul:18000/

properties:
  error: properties/error.properties
  threadpool: properties/threadPool.properties

#xxl-job admin中心配置
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://192.168.1.78:18016/xxl-job-admin
    executor:
      ip:
      port: 9051
      logpath: /home/logs/guiyu-ai-web
      logretentiondays: -1
    accessToken: 

ttsUrl: http://localhost:8080
filePath: /home/apps/ai/wav/

