server:
  id: 1  #不同toagent需修改为不一样的，取值范围1至1024
  port: 18023
spring:
  application:
    name: guiyu-callCenter-ccmanager
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 172.16.167.215 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: Toolwiz.admin.2017 # Redis服务器连接密码（默认为空）
    timeout: 5000 # 连接超时时间（毫秒）
    pool:
      max-active: 400 # 连接池最大连接数（使用负值表示没有限制
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 300 # 连接池中的最大空闲连接
      min-idle: 100 # 连接池中的最小空闲连接
  rabbitmq:
    host: 172.16.167.215
    port: 5672
    virtual-host: /
    username: guiyu
    password: Guiyu.admin.2017
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false

    
    
    
    
    
jdbc_driver0: com.mysql.jdbc.Driver
jdbc_url0: jdbc:mysql://172.16.167.215:3311/guiyu_callcenter?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC&useSSL=false
jdbc_username0: callcenter
jdbc_password0: callcenter@1234
validationQuery: SELECT 1



#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
  
#注册中心配置      
eureka:
  instance:
    #ip-address: 47.96.151.197
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/
        #defaultZone: http://192.168.1.78:18001/eureka/
properties:
  error: error.properties
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#download.path: D:\\downloads
download.path: /home/apps/callcenter/ccmanager/dowlands
#xxl-job admin中心配置
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://172.16.167.213:18016/xxl-job-admin
    executor:
      ip: 172.16.167.214
      port: 9023
      logpath: /home/logs/guiyu-callCenter-ccmanager-web
      logretentiondays: -1
    accessToken:
rabbit:
  general:
    direct:
      queue: aliyunUploadQueue|aliyunNoticeQueue|nasFileDeleteQueue #队列名称
