server:
  port: 38001
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: guiyu-tts-nas-web
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录


#fastdfs配置
fdfs:
  soTimeout: 1500         #获取文件超时时间
  connectTimeout: 600     #连接超时时间
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 172.16.167.214:22122
  pool:
    jmx-enabled: false
  webServerUrl: http://tel.guiji.ai:8080/


