server:
  port: 18020

spring:
  application:
    name: guiyu-wechat-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:none
  redis:
    database: 9
    host: 172.16.167.215
    port: 6379
    password: Toolwiz.admin.2017
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  rabbitmq:
    host: 172.16.167.215
    port: 5672
    virtual-host: /
    username: guiyu
    password: Guiyu.admin.2017
  zipkin:
    rabbitmq:
      queue: zipkin
    sleuth:
      sampler:
        percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false

#数据库连接配置
#mybatis:
#  mapper-locations: classpath*:mappers/**/*.xml
#jdbc:
#  type: mysql

#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://guiyu-cloud-registeration:18001/eureka/

#网关地址
gateway:
  host: http://guiyu-cloud-zuul:18000/

properties:
  error: properties/error.properties

rabbit:
  general:
    fanout:
      exchange: fanoutWechatUserBindExchange
      queue: fanoutWechatUserBindQueue

wechat:
  appId: wx1558a28a6907c3e8
  appSecret: ebdb772d4b503378aabc5dac1d877015
  authRedirectUrl: https://tel.guiji.ai/wechat/custom/menu/auth
  keFuUrl: https://business.guiji.ai/wx/index.html#/toChat
  keFuBindUrl: https://talk.guiji.ai/oa/manager
  keFuBindAccessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzaV9taWRkbGVfZ3JvdW5kIiwiaWF0IjoxNTUxOTMwMzc0LCJkYXRhIjp7Im9hIjoic2lfbWlkZGxlX2dyb3VuZF9vZmZpY2lhbF9hY2NvdW50In0sImV4cCI6MTg2NzI5MDM3NH0.kIFBLWkkiJtdtMWwbGSXVPSAJqnIIuQzDEXuCEzraCE
  userLoginUrl: https://tel.guiji.ai/wx/index.html#/bindPageToChat