package com.guiji.dispatch.dao;

import com.guiji.dispatch.dao.entity.Plan;
import java.util.List;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jss_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jss_plan
     *
     * @mbggenerated
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jss_plan
     *
     * @mbggenerated
     */
    Plan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jss_plan
     *
     * @mbggenerated
     */
    List<Plan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jss_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Plan record);
}