use guiyu_base;
CREATE TEMPORARY TABLE  temp_menu
    (
        id INT  COMMENT '主键',
        name VARCHAR(64) COMMENT 'app名称',
        description VARCHAR(255),
        url VARCHAR(255) NOT NULL,
        purl VARCHAR(255) COMMENT '父级url',
        permission VARCHAR(255) COMMENT '权限标识',
        is_show INT DEFAULT '0' COMMENT '是否展示0是1否',
        create_id bigint,
        create_time DATETIME,
        update_id bigint,
        update_time DATETIME,
        type INT NOT NULL COMMENT '资源类型1菜单2按钮',
        level INT NOT NULL COMMENT '资源层级',
        appid INT DEFAULT '0' COMMENT 'appid关联sys_app主键',
        remarks VARCHAR(255) COMMENT '备注信息',
        del_flag INT DEFAULT '0' NOT NULL COMMENT '删除标识0正常1删除',
        sys_type INT COMMENT '系统菜单标识：1-系统菜单 0-其他',
        PRIMARY KEY (id)
    );
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (158, '产品管理-查询', null, 'system_product_defquery', '/system/product', 'system_product_defquery', 0, 1, '2019-03-15 14:38:59', 1, '2019-03-15 14:38:59', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (159, '产品管理-新增', null, 'product_add', '/system/product', 'product_add', 0, 1, '2019-03-15 14:38:59', 1, '2019-03-15 14:38:59', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (760, '话术市场-话术制作-添加模板', null, 'botsentence_maker_addTemplate', '/botsentence/botsentence_maker', 'botsentence_maker_addTemplate', 0, 1, '2019-03-19 18:37:45', 1, '2019-03-19 18:37:45', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (761, '话术市场-话术制作-去分享', null, 'botsentence_maker_toShare', '/botsentence/botsentence_maker', 'botsentence_maker_toShare', 0, 1, '2019-03-19 18:38:42', 1, '2019-03-19 18:38:42', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (762, '话术市场-话术制作-模板编辑', null, 'botsentence_maker_edit', '/botsentence/botsentence_maker', 'botsentence_maker_edit', 0, 1, '2019-03-19 18:39:54', 1, '2019-03-19 18:39:54', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (763, '话术市场-话术制作-话术设置', null, 'botsentence_maker_setName', '/botsentence/botsentence_maker', 'botsentence_maker_setName', 0, 1, '2019-03-19 18:40:59', 1, '2019-03-19 18:40:59', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (764, '话术市场-话术制作-测试', null, 'botsentence_maker_test', '/botsentence/botsentence_maker', 'botsentence_maker_test', 0, 1, '2019-03-19 18:41:34', 1, '2019-03-19 18:41:34', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (765, '话术市场-话术制作-删除', null, 'botsentence_maker_delete', '/botsentence/botsentence_maker', 'botsentence_maker_delete', 0, 1, '2019-03-19 18:42:12', 1, '2019-03-19 18:42:12', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (766, '话术市场-话术制作-查看模板', null, 'botsentence_maker_look', '/botsentence/botsentence_maker', 'botsentence_maker_look', 0, 1, '2019-03-19 18:43:14', 1, '2019-03-19 18:43:14', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (767, '话术市场-模板市场-查看话术', null, 'botsentence_maker_market_look', '/botsentence/botsentence_maker', 'botsentence_maker_market_look', 0, 1, '2019-03-19 18:44:48', 1, '2019-03-19 18:44:48', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (768, '话术市场-模板市场-获取', null, 'botsentence_maker_market_get', '/botsentence/botsentence_maker', 'botsentence_maker_market_get', 0, 1, '2019-03-19 18:45:13', 1, '2019-03-19 18:45:13', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (769, '话术市场-话术制作-取消分享', null, 'botsentence_maker_cancelShare', '/botsentence/botsentence_maker', 'botsentence_maker_cancelShare', 0, 1, '2019-03-19 18:51:38', 1, '2019-03-19 18:51:38', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (770, '话术市场-话术审核-查看话术', null, 'botsentence_approve_look', '/botsentence/botsentence_approve', 'botsentence_approve_look', 0, 1, '2019-03-19 19:30:52', 1, '2019-03-19 19:30:52', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (771, '话术市场-话术审核-导出模板', null, 'botsentence_approve_export', '/botsentence/botsentence_approve', 'botsentence_approve_export', 0, 1, '2019-03-20 10:00:13', 1, '2019-03-20 10:00:13', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (772, '话术市场-行业模板-保存', null, 'botsentence_mytemplate_save', '/botsentence/botsentence_mytemplate', 'botsentence_mytemplate_save', 0, 1, '2019-03-20 10:03:06', 1, '2019-03-20 10:03:06', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (773, '话术市场-行业模板-导入模板', null, 'botsentence_mytemplate_import', '/botsentence/botsentence_mytemplate', 'botsentence_mytemplate_import', 0, 1, '2019-03-20 10:11:29', 1, '2019-03-20 10:15:12', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (774, '话术市场-行业模板-查看话术', null, 'botsentence_mytemplate_look', '/botsentence/botsentence_mytemplate', 'botsentence_mytemplate_look', 0, 1, '2019-03-20 10:12:56', 1, '2019-03-20 10:12:56', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (775, '话术市场-关键词库-导入', null, 'botsentence_keywords_import', '/botsentence/botsentence_keywords', 'botsentence_keywords_import', 0, 1, '2019-03-20 10:18:01', 1, '2019-03-20 10:18:01', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (776, '任务中心-任务中心-一键停止', null, 'taskCenter_phonelist_oneKeyStop', '/taskCenter/phonelist', 'phonelist_phonelist_oneKeyStop', 0, 1, '2019-03-20 10:21:43', 1, '2019-03-21 16:38:33', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (777, '话术市场-关键词审核-查看详情', null, 'botsentence_approveKeywords_look', '/botsentence/botsentence_approveKeywords', 'botsentence_approveKeywords_look', 0, 1, '2019-03-20 10:22:26', 1, '2019-03-20 10:22:26', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (778, '呼叫中心-线路管理-编辑', null, 'callCenter_lineInfoList_edit', '/callCenter/lineInfoList', 'callCenter_lineInfoList_edit', 0, 1, '2019-03-20 10:24:11', 1, '2019-03-20 10:31:22', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (779, '呼叫中心-线路管理-删除', null, 'callCenter_lineInfoList_delete', '/callCenter/lineInfoList', 'callCenter_lineInfoList_delete', 0, 1, '2019-03-20 10:25:15', 1, '2019-03-20 10:31:32', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (780, '呼叫中心-线路管理-查看线路服务', null, 'callCenter_lineInfoList_detailLines', '/callCenter/lineInfoList', 'callCenter_lineInfoList_detailLines', 0, 1, '2019-03-20 10:26:29', 1, '2019-03-20 10:31:50', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (781, '任务中心-任务中心-一键暂停', null, 'taskCenter_phonelist_oneKeyPause', '/taskCenter/phonelist', 'phonelist_phonelist_oneKeyPause', 0, 1, '2019-03-20 10:27:56', 1, '2019-03-21 16:38:40', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (782, '任务中心-一键恢复', null, 'taskCenter_phonelist_oneKeyRecover', '/taskCenter/phonelist', 'phonelist_phonelist_oneKeyRecover', 0, 1, '2019-03-20 10:28:40', 1, '2019-03-21 16:37:13', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (783, '任务中心-单个导入', null, 'taskCenter_phonelist_addPlan', '/taskCenter/phonelist', 'phonelist_phonelist_addPlan', 0, 1, '2019-03-20 10:30:30', 1, '2019-03-21 16:37:07', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (784, '任务中心-批量导入', null, 'taskCenter_phonelist_addBatchPlan', '/taskCenter/phonelist', 'phonelist_phonelist_addBatchPlan', 0, 1, '2019-03-20 10:31:10', 1, '2019-03-21 16:37:01', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (785, '通信管理-网关配置-新增设备', null, 'setPort_save', '/communicationManagement/setPort', 'setPort_save', 0, 1, '2019-03-20 10:32:00', 1, '2019-03-20 10:32:00', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (786, '任务中心-通话记录-详情', null, 'callCenter_callHistory_detail', '/callCenter/callHistory', 'callCenter_callHistory_detail', 0, 1, '2019-03-20 10:32:47', 1, '2019-03-20 10:32:47', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (787, '通信管理-网关配置-插卡', null, 'setPort_insertCard', '/communicationManagement/setPort', 'setPort_insertCard', 0, 1, '2019-03-20 10:33:25', 1, '2019-03-20 10:33:25', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (788, '任务中心-导入下拉', null, 'taskCenter_phonelist_dropdownImport', '/taskCenter/phonelist', 'phonelist_phonelist_dropdownImport', 0, 1, '2019-03-20 10:33:27', 1, '2019-03-21 16:36:53', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (789, '任务中心-一键操作下拉', null, 'taskCenter_phonelist_dropdownOneKey', '/taskCenter/phonelist', 'phonelist_phonelist_dropdownOneKey', 0, 1, '2019-03-20 10:34:06', 1, '2019-03-21 16:36:48', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (790, '任务中心-通话记录-导出对话', null, 'callCenter_callHistory_exportOne', '/callCenter/callHistory', 'callCenter_callHistory_exportOne', 0, 1, '2019-03-20 10:34:11', 1, '2019-03-20 10:34:11', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (791, '任务中心-通话记录-删除', null, 'callCenter_callHistory_delete', '/callCenter/callHistory', 'callCenter_callHistory_delete', 0, 1, '2019-03-20 10:34:44', 1, '2019-03-20 10:34:44', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (792, '任务中心-通话记录-批量导出语音', null, 'callCenter_callHistory_exportVideos', '/callCenter/callHistory', 'callCenter_callHistory_exportVideos', 0, 1, '2019-03-20 10:35:40', 1, '2019-03-20 10:35:40', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (793, '任务中心-通话记录-批量删除', null, 'callCenter_callHistory_batchDeletes', '/callCenter/callHistory', 'callCenter_callHistory_batchDeletes', 0, 1, '2019-03-20 10:36:30', 1, '2019-03-20 10:36:30', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (794, '通信管理-网关配置-换卡', null, 'setPort_changeCard', '/communicationManagement/setPort', 'setPort_changeCard', 0, 1, '2019-03-20 10:36:39', 1, '2019-03-20 10:36:39', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (795, '任务中心-详情', null, 'taskCenter_phonelist_detail', '/taskCenter/phonelist', 'phonelist_phonelist_detail', 0, 1, '2019-03-20 10:37:00', 1, '2019-03-21 16:36:41', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (796, '通信管理-网关配置-拔卡', null, 'setPort_pullCard', '/communicationManagement/setPort', 'setPort_pullCard', 0, 1, '2019-03-20 10:37:31', 1, '2019-03-20 10:37:31', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (797, '任务中心-通话记录-批量操作导出记录', null, 'callCenter_callHistory_batcnExportData', '/callCenter/callHistory', 'callCenter_callHistory_batcnExportData', 0, 1, '2019-03-20 10:38:09', 1, '2019-03-20 10:38:09', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (798, '任务中心-删除', null, 'taskCenter_phonelist_delete', '/taskCenter/phonelist', 'phonelist_phonelist_delete', 0, 1, '2019-03-20 10:38:30', 1, '2019-03-21 16:36:35', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (799, '任务中心-批量导出', null, 'taskCenter_phonelist_batchExport', '/taskCenter/phonelist', 'phonelist_phonelist_batchExport', 0, 1, '2019-03-20 10:40:01', 1, '2019-03-21 16:37:40', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (801, '呼叫中心-登记历史-导出', null, 'callCenter_checklist_exportTable', '/callCenter/checklist', 'callCenter_checklist_exportTable', 0, 1, '2019-03-20 10:40:59', 1, '2019-03-20 10:40:59', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (802, '呼叫中心-登记历史-编辑', null, 'callCenter_checklist_edit', '/callCenter/checklist', 'callCenter_checklist_edit', 0, 1, '2019-03-20 10:42:34', 1, '2019-03-20 10:43:26', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (803, '任务中心-批量加入', null, 'taskCenter_phonelist_batchJoin', '/taskCenter/phonelist', 'phonelist_phonelist_batchJoin', 0, 1, '2019-03-20 10:43:08', 1, '2019-03-21 16:37:45', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (804, '呼叫中心-登记历史-删除', null, 'callCenter_checklist_delete', '/callCenter/checklist', 'callCenter_checklist_delete', 0, 1, '2019-03-20 10:43:12', 1, '2019-03-20 10:43:12', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (805, '任务中心-批量停止', null, 'taskCenter_phonelist_batchStop', '/taskCenter/phonelist', 'phonelist_phonelist_batchStop', 0, 1, '2019-03-20 10:43:32', 1, '2019-03-21 16:37:50', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (806, '任务中心-批量暂停', null, 'taskCenter_phonelist_batchPause', '/taskCenter/phonelist', 'phonelist_phonelist_batchPause', 0, 1, '2019-03-20 10:44:00', 1, '2019-03-21 16:37:55', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (807, '任务中心-批量恢复', null, 'taskCenter_phonelist_batchRecover', '/taskCenter/phonelist', 'phonelist_phonelist_batchRecover', 0, 1, '2019-03-20 10:44:24', 1, '2019-03-21 16:38:01', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (808, '任务中心-批量删除', null, 'taskCenter_phonelist_batchDelete', '/taskCenter/phonelist', 'phonelist_phonelist_batchDelete', 0, 1, '2019-03-20 10:44:47', 1, '2019-03-21 16:38:07', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (809, '任务中心-批量操作', null, 'taskCenter_phonelist_dropdownBatch', '/taskCenter/phonelist', 'phonelist_phonelist_dropdownBatch', 0, 1, '2019-03-20 10:46:11', 1, '2019-03-21 16:38:17', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (810, '呼叫中心-坐席组管理-添加坐席组', null, 'callCenter_agentGroupManage_add', '/callCenter/agentGroupManage', 'callCenter_agentGroupManage_add', 0, 1, '2019-03-20 10:47:06', 1, '2019-03-20 10:47:06', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (811, '呼叫中心-坐席组管理-编辑', null, 'callCenter_agentGroupManage_edit', '/callCenter/agentGroupManage', 'callCenter_agentGroupManage_edit', 0, 1, '2019-03-20 10:47:44', 1, '2019-03-20 10:47:44', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (812, '呼叫中心-坐席组管理-删除', null, 'callCenter_agentGroupManage_delete', '/callCenter/agentGroupManage', 'callCenter_agentGroupManage_delete', 0, 1, '2019-03-20 10:48:18', 1, '2019-03-20 10:48:18', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (813, '任务中心-导入记录-下载', null, 'taskCenter_importRecord_download', '/taskCenter/importRecord', 'taskCenter_importRecord_download', 0, 1, '2019-03-20 10:49:34', 1, '2019-03-20 10:49:34', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (814, '任务中心-导入记录-删除', null, 'taskCenter_importRecord_delete', '/taskCenter/importRecord', 'taskCenter_importRecord_delete', 0, 1, '2019-03-20 10:50:24', 1, '2019-03-20 10:50:24', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (816, '任务中心-黑名单列表-编辑', null, 'taskCenter_blackList_edit', '/taskCenter/blackList', 'taskCenter_blackList_edit', 0, 1, '2019-03-20 10:52:51', 1, '2019-03-20 10:52:51', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (817, '任务中心-黑名单列表-删除', null, 'taskCenter_blackList_delete', '/taskCenter/blackList', 'taskCenter_blackList_delete', 0, 1, '2019-03-20 10:53:40', 1, '2019-03-20 10:53:40', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (818, '通信管理-管理员审核-审核', null, 'approveAdmin_approve', '/communicationManagement/approveAdmin', 'approveAdmin_approve', 0, 1, '2019-03-20 10:55:50', 1, '2019-03-20 10:55:50', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (819, '任务中心-黑名单列表-批量导入详情', null, 'taskCenter_blackList_batchImportDetail', '/taskCenter/blackList', 'taskCenter_blackList_batchImportDetail', 0, 1, '2019-03-20 10:56:19', 1, '2019-03-20 10:56:19', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (820, '任务中心-黑名单列表-批量导入', null, 'taskCenter_blackList_batchImport', '/taskCenter/blackList', 'taskCenter_blackList_batchImport', 0, 1, '2019-03-20 10:56:52', 1, '2019-03-20 10:56:52', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (821, '任务中心-黑名单列表-新增', null, 'taskCenter_blackList_add', '/taskCenter/blackList', 'taskCenter_blackList_add', 0, 1, '2019-03-20 10:57:19', 1, '2019-03-20 10:57:19', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (822, '短信中心-平台管理列表-新增', null, 'smsCenter_platformManage_add', '/smsCenter/platformManage', 'smsCenter_platformManage_add', 0, 1, '2019-03-20 11:00:44', 1, '2019-03-20 11:00:44', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (823, '呼叫中心-坐席成员管理-编辑', null, 'callCenter_agentStaffManage_edit', '/callCenter/agentStaffManage', 'callCenter_agentStaffManage_edit', 0, 1, '2019-03-20 11:01:43', 1, '2019-03-20 11:01:43', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (824, '短信中心-平台管理列表-删除', null, 'smsCenter_platformManage_delete', '/smsCenter/platformManage', 'smsCenter_platformManage_delete', 0, 1, '2019-03-20 11:01:50', 1, '2019-03-20 11:01:50', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (825, '短信中心-短信通道管理-新增', null, 'smsCenter_smsManage_add', '/smsCenter/smsManage', 'smsCenter_smsManage_add', 0, 1, '2019-03-20 11:05:23', 1, '2019-03-20 11:05:23', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (826, '短信中心-短信通道管理-删除', null, 'smsCenter_smsManage_delete', '/smsCenter/smsManage', 'smsCenter_smsManage_delete', 0, 1, '2019-03-20 11:06:11', 1, '2019-03-20 11:06:11', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (827, '短信中心-群发任务列表-新增', null, 'smsCenter_smsGroupTask_add', '/smsCenter/smsGroupTask', 'smsCenter_smsGroupTask_add', 0, 1, '2019-03-20 11:08:18', 1, '2019-03-20 11:08:18', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (828, '短信中心-群发任务列表-一键停止', null, 'smsCenter_smsGroupTask_onKeyStopTask', '/smsCenter/smsGroupTask', 'smsCenter_smsGroupTask_onKeyStopTask', 0, 1, '2019-03-20 11:16:46', 1, '2019-03-20 11:16:46', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (829, '短信中心-群发任务列表-已停止', null, 'smsCenter_smsGroupTask_overStop', '/smsCenter/smsGroupTask', 'smsCenter_smsGroupTask_overStop', 0, 1, '2019-03-20 11:17:25', 1, '2019-03-20 11:17:25', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (830, '短信中心-群发任务列表-编辑', null, 'smsCenter_smsGroupTask_edit', '/smsCenter/smsGroupTask', 'smsCenter_smsGroupTask_edit', 0, 1, '2019-03-20 11:17:57', 1, '2019-03-20 11:17:57', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (831, '通信管理-线路池-新增线路', null, 'lineMarket_newLine', '/communicationManagement/lineMarket', 'lineMarket_newLine', 0, 1, '2019-03-20 11:18:16', 1, '2019-03-20 11:18:16', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (832, '短信中心-群发任务列表-删除', null, 'smsCenter_smsGroupTask_delete', '/smsCenter/smsGroupTask', 'smsCenter_smsGroupTask_delete', 0, 1, '2019-03-20 11:18:22', 1, '2019-03-20 11:18:22', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (833, '短信中心-群发任务列表-审核', null, 'smsCenter_smsGroupTask_auditing', '/smsCenter/smsGroupTask', 'smsCenter_smsGroupTask_auditing', 0, 1, '2019-03-20 11:18:53', 1, '2019-03-20 11:18:53', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (834, '通信管理-线路池-编辑', null, 'lineMarket_edit', '/communicationManagement/lineMarket', 'lineMarket_edit', 0, 1, '2019-03-20 11:24:09', 1, '2019-03-20 11:26:20', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (837, '短线中心-短信配置列表-新增', null, 'smsCenter_smsConfigList_add', '/smsCenter/smsConfigList', 'smsCenter_smsConfigList_add', 0, 1, '2019-03-20 11:26:31', 1, '2019-03-20 11:26:31', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (838, '通信管理-线路池-删除', null, 'lineMarket_delete', '/communicationManagement/lineMarket', 'lineMarket_delete', 0, 1, '2019-03-20 11:26:57', 1, '2019-03-20 11:26:57', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (839, '通信管理-线路池-生效', null, 'lineMarket_effectable', '/communicationManagement/lineMarket', 'lineMarket_effectable', 0, 1, '2019-03-20 11:27:50', 1, '2019-03-20 11:27:50', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (840, '短信中心-短信配置列表-一键停止', null, 'smsCenter_smsConfigList_oneKeyStop', '/smsCenter/smsConfigList', 'smsCenter_smsConfigList_oneKeyStop', 0, 1, '2019-03-20 11:29:45', 1, '2019-03-20 11:29:45', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (841, '短信中心-短信配置列表-已停止', null, 'smsCenter_smsConfigList_overStop', '/smsCenter/smsConfigList', 'smsCenter_smsConfigList_overStop', 0, 1, '2019-03-20 11:30:30', 1, '2019-03-20 11:30:30', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (842, '短信中心-短信配置列表-编辑', null, 'smsCenter_smsConfigList_edit', '/smsCenter/smsConfigList', 'smsCenter_smsConfigList_edit', 0, 1, '2019-03-20 11:30:52', 1, '2019-03-20 11:30:52', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (843, '短信中心-短信配置列表-删除', null, 'smsCenter_smsConfigList_delete', '/smsCenter/smsConfigList', 'smsCenter_smsConfigList_delete', 0, 1, '2019-03-20 11:31:15', 1, '2019-03-20 11:31:15', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (844, '短信中心-短信配置列表-审核', null, 'smsCenter_smsConfigList_auditing', '/smsCenter/smsConfigList', 'smsCenter_smsConfigList_auditing', 0, 1, '2019-03-20 11:33:36', 1, '2019-03-20 11:33:36', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (845, '短信中心-短信发送详情-删除', null, 'smsCenter_smsSendList_delete', '/smsCenter/smsSendList', 'smsCenter_smsSendList_delete', 0, 1, '2019-03-20 11:44:05', 1, '2019-03-20 11:44:05', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (846, '机器人中心-sim卡记录-分配', null, 'robotCenter_simList_distribution', '/robotCenter/simList', 'robotCenter_simList_distribution', 0, 1, '2019-03-20 11:47:24', 1, '2019-03-20 11:47:24', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (847, '财务中心-充值管理-充值', null, 'financeCenter_rechargeManage_recharge', '/financeCenter/rechargeManage', 'financeCenter_rechargeManage_recharge', 0, 1, '2019-03-20 11:53:45', 1, '2019-03-20 11:53:45', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (848, '财务中心-充值管理-编辑', null, 'financeCenter_rechargeManage_edit', '/financeCenter/rechargeManage', 'financeCenter_rechargeManage_edit', 0, 1, '2019-03-20 11:54:26', 1, '2019-03-20 11:54:26', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (849, '财务中心-账户总览-编辑', null, 'financeCenter_accountPandect_edit', '/financeCenter/accountPandect', 'financeCenter_accountPandect_edit', 0, 1, '2019-03-20 13:20:33', 1, '2019-03-20 13:20:33', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (851, 'test差点-查询', null, 'test_test1_test3_defquery', '/test/test1/test3', 'test_test1_test3_defquery', 0, 1, '2019-03-20 16:41:51', 1, '2019-03-20 16:41:51', 2, 2, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (852, '机器人中心-机器人配置-分配详情', null, 'robotCenter_robotManage_robotDetail', '/robotCenter/robotManage', 'robotCenter_robotManage_robotDetail', 0, 1, '2019-03-20 19:14:54', 1, '2019-03-20 19:14:54', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (853, '机器人中心-机器人配置-详情页增加', null, 'robotCenter_robotManage_detailAdd', '/robotCenter/robotManage', 'robotCenter_robotManage_detailAdd', 0, 1, '2019-03-20 19:29:45', 1, '2019-03-20 19:33:35', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (854, '机器人中心-机器人配置-详情编辑', null, 'robotCenter_robotManage_detailEdit', '/robotCenter/robotManage', 'robotCenter_robotManage_detailEdit', 0, 1, '2019-03-20 19:39:43', 1, '2019-03-20 19:39:43', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (855, '机器人中心-机器人配置-详情删除', null, 'robotCenter_robotManage_detailDelete', '/robotCenter/robotManage', 'robotCenter_robotManage_detailDelete', 0, 1, '2019-03-20 19:40:23', 1, '2019-03-20 19:40:37', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (856, '量化分析-通话结果分析-导出', null, 'countAnalysis_callResultCount_exportData', '/countAnalysis/callResultCount', 'countAnalysis_callResultCount_exportData', 0, 1, '2019-03-20 19:46:00', 1, '2019-03-20 19:46:00', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (857, '呼叫中心-接待中心-提交', null, 'callCenter_workPlatform_submit', '/callCenter/workPlatform', 'callCenter_workPlatform_submit', 0, 1, '2019-03-20 19:46:57', 1, '2019-03-20 19:46:57', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (858, '呼叫中心-接待中心-人工介入', null, 'callCenter_workPlatform_helpCallHandUp', '/callCenter/workPlatform', 'callCenter_workPlatform_helpCallHandUp', 0, 1, '2019-03-20 19:47:47', 1, '2019-03-21 11:10:12', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (859, '短信中心-短信配置列表-新增', null, 'smsCenter_smsConfigList_add', '/smsCenter/smsConfigList', 'smsCenter_smsConfigList_add', 0, 1, '2019-03-21 10:23:25', 1, '2019-03-21 10:23:25', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (861, '我的信息-用户管理', null, '/personCenter/myselfInfo/userManage', '/personCenter/myselfInfo', null, 0, 1, '2019-03-21 10:28:01', 1, '2019-03-21 10:28:01', 1, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (860, '个人中心-我的信息-用户管理-绑定微信', null, 'personCenter_myselfInfo_basicInfo_bindwx', '/personCenter/myselfInfo', 'personCenter_myselfInfo_basicInfo_bindwx', 0, 1, '2019-03-21 10:26:52', 1, '2019-03-21 10:29:19', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (862, '个人中心-我的信息-用户管理-修改密码', null, 'personCenter_myselfInfo_basicInfo_revisePwd', '/personCenter/myselfInfo', 'personCenter_myselfInfo_basicInfo_revisePwd', 0, 1, '2019-03-21 10:30:32', 1, '2019-03-21 10:30:32', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (863, '个人中心-我的信息-用户管理-修改手机号', null, 'personCenter_myselfInfo_basicInfo_revisePhone', '/personCenter/myselfInfo', 'personCenter_myselfInfo_basicInfo_revisePhone', 0, 1, '2019-03-21 10:31:48', 1, '2019-03-21 10:31:48', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (864, '个人中心-我的信息-用户管理-修改邮箱', null, 'personCenter_myselfInfo_basicInfo_reviseEmail', '/personCenter/myselfInfo', 'personCenter_myselfInfo_basicInfo_reviseEmail', 0, 1, '2019-03-21 10:32:43', 1, '2019-03-21 10:32:43', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (865, '个人中心-我的信息-用户管理-解绑', null, 'personCenter_myselfInfo_basicInfo_unBindwx', '/personCenter/myselfInfo', 'personCenter_myselfInfo_basicInfo_unBindwx', 0, 1, '2019-03-21 10:37:08', 1, '2019-03-21 10:37:08', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (861, '配置管理', null, '/personCenter/myselfInfo/getData', '/personCenter/myselfInfo', null, 0, 1, '2019-03-21 10:28:01', 1, '2019-03-21 10:28:01', 1, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (861, '个人中心-我的信息-配置管理-保存', null, 'personCenter_myselfInfo_getData_save', '/personCenter/myselfInfo', 'personCenter_myselfInfo_getData_save', 0, 1, '2019-03-21 10:28:01', 1, '2019-03-21 10:28:01', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (866, '系统管理-组织管理-新增', null, 'system_organization_add', '/system/organization', 'system_organization_add', 0, 1, '2019-03-21 10:50:39', 1, '2019-03-21 10:50:39', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (867, '系统管理-组织管理-编辑', null, 'system_organization_edit', '/system/organization', 'system_organization_edit', 0, 1, '2019-03-21 10:51:01', 1, '2019-03-21 10:51:01', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (868, '系统管理-组织管理-删除', null, 'system_organization_delete', '/system/organization', 'system_organization_delete', 0, 1, '2019-03-21 10:51:27', 1, '2019-03-21 10:51:27', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (869, '系统管理-开户管理-新增账户', null, 'system_account_add', '/system/account', 'system_account_add', 0, 1, '2019-03-21 10:55:43', 1, '2019-03-21 10:55:43', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (870, '系统管理-开户管理-绑定话术', null, 'system_account_speech', '/system/account', 'system_account_speech', 0, 1, '2019-03-21 10:56:13', 1, '2019-03-21 10:56:13', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (871, '系统管理-开户管理-配置机器人', null, 'system_account_robot', '/system/account', 'system_account_robot', 0, 1, '2019-03-21 10:56:41', 1, '2019-03-21 10:56:41', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (873, '系统管理-用户管理-新增', null, 'system_usr_add', '/system/user', 'system_usr_add', 0, 1, '2019-03-21 11:01:54', 1, '2019-03-21 11:01:54', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (874, '系统管理-用户管理-编辑', null, 'system_usr_edit', '/system/user', 'system_usr_edit', 0, 1, '2019-03-21 11:02:20', 1, '2019-03-21 11:02:20', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (875, '系统管理-用户管理-配资资源', null, 'system_usr_configResource', '/system/user', 'system_usr_configResource', 0, 1, '2019-03-21 11:02:58', 1, '2019-03-21 11:02:58', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (876, '系统管理-数据字典-新增', null, 'system_dataDictionaries_add', '/system/dataDictionaries', 'system_dataDictionaries_add', 0, 1, '2019-03-21 14:30:50', 1, '2019-03-21 14:30:50', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (877, '系统管理-数据字典-编辑', null, 'system_dataDictionaries_edit', '/system/dataDictionaries', 'system_dataDictionaries_edit', 0, 1, '2019-03-21 14:31:52', 1, '2019-03-21 14:31:52', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (878, '系统管理-数据字典-删除', null, 'system_dataDictionaries_delete', '/system/dataDictionaries', 'system_dataDictionaries_delete', 0, 1, '2019-03-21 14:32:12', 1, '2019-03-21 14:32:12', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (879, '系统管理-公告列表-删除', null, 'system_noticeList_delete', '/system/noticeList', 'system_noticeList_delete', 0, 1, '2019-03-21 14:33:57', 1, '2019-03-21 14:33:57', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (880, '系统管理-公告列表-新增', null, 'system_noticeList_add', '/system/noticeList', 'system_noticeList_add', 0, 1, '2019-03-21 14:34:20', 1, '2019-03-21 14:34:20', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (881, '系统管理-进程管理-查看进程', null, 'system_processManage_cat', '/system/processManage', 'system_processManage_cat', 0, 1, '2019-03-21 14:41:13', 1, '2019-03-21 14:41:13', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (882, '系统管理-进程管理-重启', null, 'system_processManage_restart', '/system/processManage', 'system_processManage_restart', 0, 1, '2019-03-21 14:41:44', 1, '2019-03-21 14:41:44', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (883, '系统管理-权限管理-新增', null, 'system_role_add', '/system/auth', 'system_role_add', 0, 1, '2019-03-21 14:46:55', 1, '2019-03-21 14:46:55', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (884, '系统管理-权限管理-编辑', null, 'system_role_edit', '/system/auth', 'system_role_edit', 0, 1, '2019-03-21 14:47:15', 1, '2019-03-21 14:47:15', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (885, '系统管理-权限管理-删除', null, 'system_role_delete', '/system/auth', 'system_role_delete', 0, 1, '2019-03-21 14:47:40', 1, '2019-03-21 14:47:40', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (886, '系统管理-菜单管理-新增', null, 'system_menu_add', '/system/menu', 'system_menu_add', 0, 1, '2019-03-21 14:52:10', 1, '2019-03-21 14:52:10', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (887, '系统管理-菜单管理-编辑', null, 'system_menu_edit', '/system/menu', 'system_menu_edit', 0, 1, '2019-03-21 14:52:37', 1, '2019-03-21 14:52:37', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (888, '系统管理-菜单管理-删除', null, 'system_menu_delete', '/system/menu', 'system_menu_delete', 0, 1, '2019-03-21 14:53:04', 1, '2019-03-21 14:53:04', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (889, '消息中心-站内信-删除', null, 'newsCenter_newsMail_delete', '/newsCenter/newsMail', 'newsCenter_newsMail_delete', 0, 1, '2019-03-21 14:59:35', 1, '2019-03-21 14:59:35', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (890, '消息中心-提示设置-恢复默认', null, 'newsCenter_receiveSetting_reDefault', '/newsCenter/receiveSetting', 'newsCenter_receiveSetting_reDefault', 0, 1, '2019-03-21 15:02:09', 1, '2019-03-21 15:02:09', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (891, '消息中心-提醒设置-消息接收人', null, 'newsCenter_receiveSetting_editReceiver', '/newsCenter/receiveSetting', 'newsCenter_receiveSetting_editReceiver', 0, 1, '2019-03-21 15:04:30', 1, '2019-03-21 15:04:30', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (892, '消息中心-提醒设置-修改意向标签', null, 'newsCenter_receiveSetting_noticeType1', '/newsCenter/receiveSetting', 'newsCenter_receiveSetting_noticeType1', 0, 1, '2019-03-21 15:06:12', 1, '2019-03-21 15:06:12', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (893, '系统管理-产品管理-新增', null, 'system_productManagement_add', '/system/product', 'system_productManagement_add', 0, 1, '2019-03-21 15:13:34', 1, '2019-03-21 15:13:34', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (894, '系统管理-产品管理-编辑', null, 'system_productManagement_edit', '/system/product', 'system_productManagement_edit', 0, 1, '2019-03-21 15:13:52', 1, '2019-03-21 15:13:52', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (895, '系统管理-产品管理-删除', null, 'system_productManagement_delete', '/system/product', 'system_productManagement_delete', 0, 1, '2019-03-21 15:14:13', 1, '2019-03-21 15:14:13', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (897, '批次管理-查询', null, 'taskCenter_phonelist_batchManage_defquery', '/taskCenter/phonelist/batchManage', 'taskCenter:phonelist:batchManage', 0, 1, '2019-03-23 14:39:32', 1, '2019-03-23 14:39:32', 2, 4, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (899, '任务中心-全部-查询', null, 'taskCenter_phonelist_phonelisContent_defquery', '/taskCenter/phonelist/phonelisContent', 'taskCenter:phonelist:phonelisContent', 0, 1, '2019-03-23 15:30:11', 1, '2019-03-23 15:30:11', 2, 4, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (900, '通信管理-线路市场-全部', null, 'communicationManagement_comManage_all', '/communicationManagement/comManage', 'communicationManagement_comManage_all', 0, 1, '2019-03-25 19:27:12', 1, '2019-03-25 19:27:12', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (902, '通信管理-线路市场-我的SIM卡', null, 'communicationManagement_comManage_mySIMCard', '/communicationManagement/comManage', 'communicationManagement_comManage_mySIMCard', 0, 1, '2019-03-25 19:28:31', 1, '2019-03-25 19:28:31', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (903, '通信管理-线路市场-申请历史', null, 'communicationManagement_comManage_applyHistory', '/communicationManagement/comManage', 'communicationManagement_comManage_applyHistory', 0, 1, '2019-03-25 19:29:20', 1, '2019-03-25 19:29:20', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (904, '通信管理-线路市场-我的线路', null, 'communicationManagement_comManage_myLines', '/communicationManagement/comManage', 'communicationManagement_comManage_myLines', 0, 1, '2019-03-25 19:29:20', 1, '2019-03-25 19:29:20', 2, 3, 0, 'add', 0, null);
INSERT INTO temp_menu (id, name, description, url, purl, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) VALUES (800, '通信管理-线路市场-申请', null, 'comManage_application', '/communicationManagement/comManage', 'comManage_application', 0, 1, '2019-03-20 10:40:41', 1, '2019-03-20 10:40:41', 2, 3, 0, 'add', 0, null);


INSERT INTO sys_menu (name, description, url, pid, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) select s2.name, s2.description, s2.url, s1.id, s2.permission, s2.is_show, s2.create_id, s2.create_time, s2.update_id, s2.update_time, s2.type, s2.level, s2.appid, s2.remarks, s2.del_flag, s2.sys_type from sys_menu s1,temp_menu s2 where s1.url=s2.purl;