use guiyu_base;
CREATE TEMPORARY TABLE  temp_menu
    (
        id INT  COMMENT '主键',
        name VARCHAR(64) COMMENT 'app名称',
        description VARCHAR(255),
        url VARCHAR(255) NOT NULL,
        purl VARCHAR(255) COMMENT '父级url',
        permission VARCHAR(255) COMMENT '权限标识',
        is_show INT DEFAULT '0' COMMENT '是否展示0是1否',
        create_id bigint,
        create_time DATETIME,
        update_id bigint,
        update_time DATETIME,
        type INT NOT NULL COMMENT '资源类型1菜单2按钮',
        level INT NOT NULL COMMENT '资源层级',
        appid INT DEFAULT '0' COMMENT 'appid关联sys_app主键',
        remarks VARCHAR(255) COMMENT '备注信息',
        del_flag INT DEFAULT '0' NOT NULL COMMENT '删除标识0正常1删除',
        sys_type INT COMMENT '系统菜单标识：1-系统菜单 0-其他',
        PRIMARY KEY (id)
    );
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('886', '系统管理-菜单管理-新增', NULL, 'system_menu_add', '11', 'system_menu_add', '0', '1', '2019-03-21 14:52:10', '1', '2019-03-21 14:52:10', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('887', '系统管理-菜单管理-编辑', NULL, 'system_menu_edit', '11', 'system_menu_edit', '0', '1', '2019-03-21 14:52:37', '1', '2019-03-21 14:52:37', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('888', '系统管理-菜单管理-删除', NULL, 'system_menu_delete', '11', 'system_menu_delete', '0', '1', '2019-03-21 14:53:04', '1', '2019-03-21 14:53:04', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('889', '通信管理-线路市场-申请历史', NULL, 'communicationManagement_comManage_applyHistory', '116', 'communicationManagement_comManage_applyHistory', '0', '1', '2019-04-07 14:09:35', '1', '2019-04-07 14:09:35', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('890', '通信管理-线路市场-我的SIM卡', NULL, 'communicationManagement_comManage_mySIMCard', '116', 'communicationManagement_comManage_mySIMCard', '0', '1', '2019-04-07 14:10:09', '1', '2019-04-07 14:10:09', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('891', '通讯管理-线路市场-全部', NULL, 'communicationManagement_comManage_all', '116', 'communicationManagement_comManage_all', '0', '1', '2019-04-07 14:10:47', '1', '2019-04-07 14:10:47', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('892', '通讯管理-线路市场-我的线路', NULL, 'communicationManagement_comManage_myLines', '116', 'communicationManagement_comManage_myLines', '0', '1', '2019-04-07 14:11:31', '1', '2019-04-07 14:11:31', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('893', '个人信息-用户管理', NULL, '/personCenter/myselfInfo/userManage', '19', NULL, '0', '1', '2019-04-07 14:12:31', '1', '2019-04-07 14:12:31', '1', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('895', '配置管理', NULL, '/personCenter/myselfInfo/getData', '19', NULL, '0', '1', '2019-04-07 14:13:09', '1', '2019-04-07 14:13:09', '1', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('897', '任务中心-任务列表-一键停止', NULL, 'taskCenter_phonelist_oneKeyStop', '7', 'taskCenter_phonelist_oneKeyStop', '0', '1', '2019-04-08 09:32:58', '1', '2019-04-08 09:34:59', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('898', '任务中心-任务列表-一键暂停', NULL, 'taskCenter_phonelist_oneKeyPause', '7', 'taskCenter_phonelist_oneKeyPause', '0', '1', '2019-04-08 09:33:22', '1', '2019-04-08 09:34:35', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('899', '任务中心-任务列表-一键恢复', NULL, 'taskCenter_phonelist_oneKeyRecover', '7', 'taskCenter_phonelist_oneKeyRecover', '0', '1', '2019-04-08 09:34:10', '1', '2019-04-08 09:34:10', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('900', '任务中心-任务列表-单个导入', NULL, 'taskCenter_phonelist_addPlan', '7', 'taskCenter_phonelist_addPlan', '0', '1', '2019-04-08 09:36:19', '1', '2019-04-08 09:36:19', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('901', '任务中心-任务列表-批量导入', NULL, 'taskCenter_phonelist_addBatchPlan', '7', 'taskCenter_phonelist_addBatchPlan', '0', '1', '2019-04-08 09:37:23', '1', '2019-04-08 09:37:23', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('902', '任务中心-任务列表-详情', NULL, 'taskCenter_phonelist_detail', '7', 'taskCenter_phonelist_detail', '0', '1', '2019-04-08 09:38:00', '1', '2019-04-08 09:38:00', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('903', '任务中心-任务列表-删除', NULL, 'taskCenter_phonelist_delete', '7', 'taskCenter_phonelist_delete', '0', '1', '2019-04-08 09:38:31', '1', '2019-04-08 09:38:31', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('904', '任务中心-任务列表-批量导出', NULL, 'taskCenter_phonelist_batchExport', '7', 'taskCenter_phonelist_batchExport', '0', '1', '2019-04-08 09:39:00', '1', '2019-04-08 09:39:00', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('905', '任务中心-任务列表-批量加入', NULL, 'taskCenter_phonelist_batchJoin', '7', 'taskCenter_phonelist_batchJoin', '0', '1', '2019-04-08 09:39:29', '1', '2019-04-08 09:39:29', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('906', '任务中心-任务列表-批量停止', NULL, 'taskCenter_phonelist_batchStop', '7', 'taskCenter_phonelist_batchStop', '0', '1', '2019-04-08 09:39:54', '1', '2019-04-08 09:39:54', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('907', '任务中心-任务列表-批量暂停', NULL, 'taskCenter_phonelist_batchPause', '7', 'taskCenter_phonelist_batchPause', '0', '1', '2019-04-08 09:40:33', '1', '2019-04-08 09:40:33', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('908', '任务中心-任务列表-批量恢复', NULL, 'taskCenter_phonelist_batchRecover', '7', 'taskCenter_phonelist_batchRecover', '0', '1', '2019-04-08 09:41:03', '1', '2019-04-08 09:41:03', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('909', '任务中心-任务列表-批量删除', NULL, 'taskCenter_phonelist_batchDelete', '7', 'taskCenter_phonelist_batchDelete', '0', '1', '2019-04-08 09:41:34', '1', '2019-04-08 09:41:34', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('910', '任务中心-导入记录-下载', NULL, 'taskCenter_importRecord_download', '111', 'taskCenter_importRecord_download', '0', '1', '2019-04-08 09:44:06', '1', '2019-04-08 09:44:06', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('911', '任务中心-导入记录-删除', NULL, 'taskCenter_importRecord_delete', '111', 'taskCenter_importRecord_delete', '0', '1', '2019-04-08 09:44:26', '1', '2019-04-08 09:44:26', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('912', '任务中心-黑名单列表-编辑', NULL, 'taskCenter_blackList_edit', '93', 'taskCenter_blackList_edit', '0', '1', '2019-04-08 09:46:15', '1', '2019-04-08 09:46:15', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('913', '任务中心-黑名单列表-删除', NULL, 'taskCenter_blackList_delete', '93', 'taskCenter_blackList_delete', '0', '1', '2019-04-08 09:46:52', '1', '2019-04-08 09:46:52', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('914', '任务中心-黑名单列表-批量导入详情', NULL, 'taskCenter_blackList_batchImportDetail', '93', 'taskCenter_blackList_batchImportDetail', '0', '1', '2019-04-08 09:47:15', '1', '2019-04-08 09:47:15', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('915', '任务中心-黑名单列表-批量导入', NULL, 'taskCenter_blackList_batchImport', '93', 'taskCenter_blackList_batchImport', '0', '1', '2019-04-08 09:47:37', '1', '2019-04-08 09:47:37', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('916', '任务中心-黑名单列表-新增', NULL, 'taskCenter_blackList_add', '93', 'taskCenter_blackList_add', '0', '1', '2019-04-08 09:48:02', '1', '2019-04-08 09:48:02', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('917', '短信中心-平台管理列表-新增', NULL, 'smsCenter_platformManage_add', '103', 'smsCenter_platformManage_add', '0', '1', '2019-04-08 09:49:22', '1', '2019-04-08 09:49:22', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('918', '短信中心-平台管理列表-删除', NULL, 'smsCenter_platformManage_delete', '103', 'smsCenter_platformManage_delete', '0', '1', '2019-04-08 09:49:44', '1', '2019-04-08 09:49:44', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('919', '短信中心-群发任务列表-新增', NULL, 'smsCenter_smsGroupTask_add', '105', 'smsCenter_smsGroupTask_add', '0', '1', '2019-04-08 09:50:25', '1', '2019-04-08 09:50:25', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('920', '短信中心-群发任务列表-一键停止', NULL, 'smsCenter_smsGroupTask_onKeyStopTask', '105', 'smsCenter_smsGroupTask_onKeyStopTask', '0', '1', '2019-04-08 09:51:00', '1', '2019-04-08 09:51:00', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('921', '短信中心-群发任务列表-已停止', NULL, 'smsCenter_smsGroupTask_overStop', '105', 'smsCenter_smsGroupTask_overStop', '0', '1', '2019-04-08 09:51:19', '1', '2019-04-08 09:51:19', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('922', '短信中心-群发任务列表-编辑', NULL, 'smsCenter_smsGroupTask_edit', '105', 'smsCenter_smsGroupTask_edit', '0', '1', '2019-04-08 09:51:40', '1', '2019-04-08 09:51:40', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('923', '短信中心-群发任务列表-删除', NULL, 'smsCenter_smsGroupTask_delete', '105', 'smsCenter_smsGroupTask_delete', '0', '1', '2019-04-08 09:52:00', '1', '2019-04-08 09:52:00', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('924', '短信中心-群发任务列表-审核', NULL, 'smsCenter_smsGroupTask_auditing', '105', 'smsCenter_smsGroupTask_auditing', '0', '1', '2019-04-08 09:52:23', '1', '2019-04-08 09:52:23', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('925', '短信中心-短信通道管理-新增', NULL, 'smsCenter_smsManage_add', '104', 'smsCenter_smsManage_add', '0', '1', '2019-04-08 09:53:02', '1', '2019-04-08 09:53:02', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('926', '短信中心-短信通道管理-删除', NULL, 'smsCenter_smsManage_delete', '104', 'smsCenter_smsManage_delete', '0', '1', '2019-04-08 09:53:24', '1', '2019-04-08 09:53:24', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('927', '短信中心-短信发送详情-删除', NULL, 'smsCenter_smsSendList_delete', '107', 'smsCenter_smsSendList_delete', '0', '1', '2019-04-08 09:54:12', '1', '2019-04-08 09:54:12', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('928', '短线中心-短信配置列表-新增', NULL, 'smsCenter_smsConfigList_add', '106', 'smsCenter_smsConfigList_add', '0', '1', '2019-04-08 09:54:46', '1', '2019-04-08 09:54:46', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('929', '短信中心-短信配置列表-一键停止', NULL, 'smsCenter_smsConfigList_oneKeyStop', '106', 'smsCenter_smsConfigList_oneKeyStop', '0', '1', '2019-04-08 09:55:08', '1', '2019-04-08 09:55:08', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('930', '短信中心-短信配置列表-已停止', NULL, 'smsCenter_smsConfigList_overStop', '106', 'smsCenter_smsConfigList_overStop', '0', '1', '2019-04-08 09:55:28', '1', '2019-04-08 09:55:28', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('931', '短信中心-短信配置列表-编辑', NULL, 'smsCenter_smsConfigList_edit', '106', 'smsCenter_smsConfigList_edit', '0', '1', '2019-04-08 09:55:52', '1', '2019-04-08 09:55:52', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('932', '短信中心-短信配置列表-删除', NULL, 'smsCenter_smsConfigList_delete', '106', 'smsCenter_smsConfigList_delete', '0', '1', '2019-04-08 09:56:23', '1', '2019-04-08 09:56:23', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('933', '短信中心-短信配置列表-审核', NULL, 'smsCenter_smsConfigList_auditing', '106', 'smsCenter_smsConfigList_auditing', '0', '1', '2019-04-08 09:56:52', '1', '2019-04-08 09:56:52', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('934', '个人中心-我的信息-用户管理-绑定微信', NULL, 'personCenter_myselfInfo_basicInfo_bindwx', '893', 'personCenter_myselfInfo_basicInfo_bindwx', '0', '1', '2019-04-08 09:59:35', '1', '2019-04-08 09:59:35', '2', '4', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('935', '个人中心-我的信息-用户管理-修改密码', NULL, 'personCenter_myselfInfo_basicInfo_revisePwd', '893', 'personCenter_myselfInfo_basicInfo_revisePwd', '0', '1', '2019-04-08 10:00:05', '1', '2019-04-08 10:00:05', '2', '4', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('936', '个人中心-我的信息-用户管理-修改手机号', NULL, 'personCenter_myselfInfo_basicInfo_revisePhone', '893', 'personCenter_myselfInfo_basicInfo_revisePhone', '0', '1', '2019-04-08 10:00:27', '1', '2019-04-08 10:00:27', '2', '4', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('937', '个人中心-我的信息-用户管理-修改邮箱', NULL, 'personCenter_myselfInfo_basicInfo_reviseEmail', '893', 'personCenter_myselfInfo_basicInfo_reviseEmail', '0', '1', '2019-04-08 10:00:54', '1', '2019-04-08 10:00:54', '2', '4', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('938', '个人中心-我的信息-用户管理-解绑', NULL, 'personCenter_myselfInfo_basicInfo_unBindwx', '893', 'personCenter_myselfInfo_basicInfo_unBindwx', '0', '1', '2019-04-08 10:01:22', '1', '2019-04-08 10:01:22', '2', '4', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('939', '个人中心-我的信息-配置管理-保存', NULL, 'personCenter_myselfInfo_getData_save', '895', 'personCenter_myselfInfo_getData_save', '0', '1', '2019-04-08 10:01:49', '1', '2019-04-08 10:01:49', '2', '4', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('940', '财务中心-账户总览-编辑', NULL, 'financeCenter_accountPandect_edit', '120', 'financeCenter_accountPandect_edit', '0', '1', '2019-04-08 10:04:20', '1', '2019-04-08 10:04:20', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('941', '财务中心-充值管理-充值', NULL, 'financeCenter_rechargeManage_recharge', '122', 'financeCenter_rechargeManage_recharge', '0', '1', '2019-04-08 10:05:18', '1', '2019-04-08 10:05:18', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('942', '财务中心-充值管理-编辑', NULL, 'financeCenter_rechargeManage_edit', '122', 'financeCenter_rechargeManage_edit', '0', '1', '2019-04-08 10:05:42', '1', '2019-04-08 10:05:42', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('943', '系统管理-组织管理-新增', NULL, 'system_organization_add', '99', 'system_organization_add', '0', '1', '2019-04-08 10:08:19', '1', '2019-04-08 10:08:19', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('944', '系统管理-组织管理-编辑', NULL, 'system_organization_edit', '99', 'system_organization_edit', '0', '1', '2019-04-08 10:08:47', '1', '2019-04-08 10:08:47', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('945', '系统管理-组织管理-删除', NULL, 'system_organization_delete', '99', 'system_organization_delete', '0', '1', '2019-04-08 10:09:11', '1', '2019-04-08 10:09:11', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('946', '产品管理', NULL, '/system/product', '1', NULL, '0', '1', '2019-04-08 10:11:22', '1', '2019-04-08 10:11:22', '1', '2', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('948', '系统管理-产品管理-新增', NULL, 'system_productManagement_add', '946', 'system_productManagement_add', '0', '1', '2019-04-08 10:11:41', '1', '2019-04-08 10:11:41', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('949', '系统管理-产品管理-编辑', NULL, 'system_productManagement_edit', '946', 'system_productManagement_edit', '0', '1', '2019-04-08 10:12:06', '1', '2019-04-08 10:12:06', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('950', '系统管理-产品管理-删除', NULL, 'system_productManagement_delete', '946', 'system_productManagement_delete', '0', '1', '2019-04-08 10:12:38', '1', '2019-04-08 10:12:38', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('951', '系统管理-开户管理-新增账户', NULL, 'system_account_add', '100', 'system_account_add', '0', '1', '2019-04-08 10:13:27', '1', '2019-04-08 10:13:27', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('952', '系统管理-开户管理-绑定话术', NULL, 'system_account_speech', '100', 'system_account_speech', '0', '1', '2019-04-08 10:13:50', '1', '2019-04-08 10:13:50', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('953', '系统管理-开户管理-配置机器人', NULL, 'system_account_robot', '100', 'system_account_robot', '0', '1', '2019-04-08 10:14:16', '1', '2019-04-08 10:14:16', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('954', '系统管理-用户管理-新增', NULL, 'system_usr_add', '2', 'system_usr_add', '0', '1', '2019-04-08 10:14:59', '1', '2019-04-08 10:14:59', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('955', '系统管理-用户管理-编辑', NULL, 'system_usr_edit', '2', 'system_usr_edit', '0', '1', '2019-04-08 10:15:19', '1', '2019-04-08 10:15:19', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('956', '系统管理-用户管理-配资资源', NULL, 'system_usr_configResource', '2', 'system_usr_configResource', '0', '1', '2019-04-08 10:15:42', '1', '2019-04-08 10:15:42', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('957', '系统管理-权限管理-新增', NULL, 'system_role_add', '10', 'system_role_add', '0', '1', '2019-04-08 10:16:20', '1', '2019-04-08 10:16:20', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('958', '系统管理-权限管理-编辑', NULL, 'system_role_edit', '10', 'system_role_edit', '0', '1', '2019-04-08 10:16:39', '1', '2019-04-08 10:16:39', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('959', '系统管理-权限管理-删除', NULL, 'system_role_delete', '10', 'system_role_delete', '0', '1', '2019-04-08 10:16:58', '1', '2019-04-08 10:16:58', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('960', '系统管理-数据字典-新增', NULL, 'system_dataDictionaries_add', '18', 'system_dataDictionaries_add', '0', '1', '2019-04-08 10:18:08', '1', '2019-04-08 10:18:08', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('961', '系统管理-数据字典-编辑', NULL, 'system_dataDictionaries_edit', '18', 'system_dataDictionaries_edit', '0', '1', '2019-04-08 10:18:30', '1', '2019-04-08 10:18:30', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('962', '系统管理-数据字典-删除', NULL, 'system_dataDictionaries_delete', '18', 'system_dataDictionaries_delete', '0', '1', '2019-04-08 10:18:50', '1', '2019-04-08 10:18:50', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('963', '系统管理-进程管理-查看进程', NULL, 'system_processManage_cat', '22', 'system_processManage_cat', '0', '1', '2019-04-08 10:19:48', '1', '2019-04-08 10:19:48', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('964', '系统管理-进程管理-重启', NULL, 'system_processManage_restart', '22', 'system_processManage_restart', '0', '1', '2019-04-08 10:20:10', '1', '2019-04-08 10:20:10', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('965', '系统管理-公告列表-删除', NULL, 'system_noticeList_delete', '108', 'system_noticeList_delete', '0', '1', '2019-04-08 10:20:48', '1', '2019-04-08 10:20:48', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('966', '系统管理-公告列表-新增', NULL, 'system_noticeList_add', '108', 'system_noticeList_add', '0', '1', '2019-04-08 10:21:16', '1', '2019-04-08 10:21:16', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('967', '通信管理-网关配置-新增设备', NULL, 'setPort_save', '115', 'setPort_save', '0', '1', '2019-04-08 10:22:25', '1', '2019-04-08 10:22:25', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('968', '通信管理-网关配置-插卡', NULL, 'setPort_insertCard', '115', 'setPort_insertCard', '0', '1', '2019-04-08 10:22:47', '1', '2019-04-08 10:22:47', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('969', '通信管理-网关配置-换卡', NULL, 'setPort_changeCard', '115', 'setPort_changeCard', '0', '1', '2019-04-08 10:23:12', '1', '2019-04-08 10:23:12', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('970', '通信管理-网关配置-拔卡', NULL, 'setPort_pullCard', '115', 'setPort_pullCard', '0', '1', '2019-04-08 10:23:49', '1', '2019-04-08 10:23:49', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('971', '通信管理-管理员审核-审核', NULL, 'approveAdmin_approve', '117', 'approveAdmin_approve', '0', '1', '2019-04-08 10:26:25', '1', '2019-04-08 10:26:25', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('972', '通信管理-线路池-新增线路', NULL, 'lineMarket_newLine', '118', 'lineMarket_newLine', '0', '1', '2019-04-08 10:26:56', '1', '2019-04-08 10:26:56', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('973', '通信管理-线路池-编辑', NULL, 'lineMarket_edit', '118', 'lineMarket_edit', '0', '1', '2019-04-08 10:27:15', '1', '2019-04-08 10:27:15', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('974', '通信管理-线路池-删除', NULL, 'lineMarket_delete', '118', 'lineMarket_delete', '0', '1', '2019-04-08 10:27:35', '1', '2019-04-08 10:27:35', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('975', '通信管理-线路池-生效', NULL, 'lineMarket_effectable', '118', 'lineMarket_effectable', '0', '1', '2019-04-08 10:27:52', '1', '2019-04-08 10:27:52', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('976', '量化分析-通话结果分析-导出', NULL, 'countAnalysis_callResultCount_exportData', '88', 'countAnalysis_callResultCount_exportData', '0', '1', '2019-04-08 10:33:24', '1', '2019-04-08 10:33:24', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('981', '呼叫中心-通话记录-详情', NULL, 'callCenter_callHistory_detail', '9', 'callCenter_callHistory_detail', '0', '1', '2019-04-08 10:40:03', '1', '2019-04-08 10:40:03', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('982', '呼叫中心-通话记录-导出对话', NULL, 'callCenter_callHistory_exportOne', '9', 'callCenter_callHistory_exportOne', '0', '1', '2019-04-08 10:40:30', '1', '2019-04-08 10:40:30', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('985', '呼叫中心-通话记录-删除', NULL, 'callCenter_callHistory_delete', '9', 'callCenter_callHistory_delete', '0', '1', '2019-04-08 10:41:04', '1', '2019-04-08 10:41:04', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('988', '呼叫中心-通话记录-批量导出语音', NULL, 'callCenter_callHistory_exportVideos', '9', 'callCenter_callHistory_exportVideos', '0', '1', '2019-04-08 10:41:27', '1', '2019-04-08 10:41:27', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('989', '呼叫中心-通话记录-批量删除', NULL, 'callCenter_callHistory_batchDeletes', '9', 'callCenter_callHistory_batchDeletes', '0', '1', '2019-04-08 10:42:21', '1', '2019-04-08 10:42:21', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('990', '呼叫中心-通话记录-批量操作导出记录', NULL, 'callCenter_callHistory_batcnExportData', '9', 'callCenter_callHistory_batcnExportData', '0', '1', '2019-04-08 10:42:44', '1', '2019-04-08 10:42:44', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('991', '呼叫中心-接待中心-提交', NULL, 'callCenter_workPlatform_submit', '125', 'callCenter_workPlatform_submit', '0', '1', '2019-04-08 10:43:12', '1', '2019-04-08 10:43:12', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('992', '呼叫中心-接待中心-人工介入', NULL, 'callCenter_workPlatform_helpCallHandUp', '125', 'callCenter_workPlatform_helpCallHandUp', '0', '1', '2019-04-08 10:43:36', '1', '2019-04-08 10:43:36', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('993', '呼叫中心-登记历史-导出', NULL, 'callCenter_checklist_exportTable', '126', 'callCenter_checklist_exportTable', '0', '1', '2019-04-08 10:44:02', '1', '2019-04-08 10:44:02', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('994', '呼叫中心-登记历史-编辑', NULL, 'callCenter_checklist_edit', '126', 'callCenter_checklist_edit', '0', '1', '2019-04-08 10:44:29', '1', '2019-04-08 10:44:29', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('995', '呼叫中心-登记历史-删除', NULL, 'callCenter_checklist_delete', '126', 'callCenter_checklist_delete', '0', '1', '2019-04-08 10:44:51', '1', '2019-04-08 10:44:51', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('996', '呼叫中心-坐席组管理-添加坐席组', NULL, 'callCenter_agentGroupManage_add', '127', 'callCenter_agentGroupManage_add', '0', '1', '2019-04-08 10:45:22', '1', '2019-04-08 10:45:22', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('997', '呼叫中心-坐席组管理-编辑', NULL, 'callCenter_agentGroupManage_edit', '127', 'callCenter_agentGroupManage_edit', '0', '1', '2019-04-08 10:45:46', '1', '2019-04-08 10:45:46', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('998', '呼叫中心-坐席组管理-删除', NULL, 'callCenter_agentGroupManage_delete', '127', 'callCenter_agentGroupManage_delete', '0', '1', '2019-04-08 10:46:05', '1', '2019-04-08 10:46:05', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('999', '呼叫中心-坐席成员管理-编辑', NULL, 'callCenter_agentStaffManage_edit', '128', 'callCenter_agentStaffManage_edit', '0', '1', '2019-04-08 10:46:42', '1', '2019-04-08 10:46:42', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1000', '机器人中心-机器人配置-分配详情', NULL, 'robotCenter_robotManage_robotDetail', '17', 'robotCenter_robotManage_robotDetail', '0', '1', '2019-04-08 10:47:19', '1', '2019-04-08 10:47:19', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1004', '机器人中心-机器人配置-详情编辑', NULL, 'robotCenter_robotManage_detailEdit', '17', 'robotCenter_robotManage_detailEdit', '0', '1', '2019-04-08 10:49:52', '1', '2019-04-08 10:49:52', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1008', '话术市场-话术制作-添加模板', NULL, 'botsentence_maker_addTemplate', '13', 'botsentence_maker_addTemplate', '0', '1', '2019-04-08 10:58:07', '1', '2019-04-08 10:58:07', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1009', '话术市场-关键词审核-查看详情', NULL, 'botsentence_approveKeywords_look', '135', 'botsentence_approveKeywords_look', '0', '1', '2019-04-08 10:58:14', '1', '2019-04-08 10:58:14', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1010', '话术市场-话术制作-去分享', NULL, 'botsentence_maker_toShare', '13', 'botsentence_maker_toShare', '0', '1', '2019-04-08 10:58:29', '1', '2019-04-08 10:58:29', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1011', '话术市场-关键词库-导入', NULL, 'botsentence_keywords_import', '109', 'botsentence_keywords_import', '0', '1', '2019-04-08 10:58:37', '1', '2019-04-08 10:58:37', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1012', '话术市场-话术制作-模板编辑', NULL, 'botsentence_maker_edit', '13', 'botsentence_maker_edit', '0', '1', '2019-04-08 10:58:51', '1', '2019-04-08 10:58:51', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1013', '话术市场-行业模板-查看话术', NULL, 'botsentence_mytemplate_look', '15', 'botsentence_mytemplate_look', '0', '1', '2019-04-08 10:59:14', '1', '2019-04-08 10:59:14', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1014', '话术市场-话术制作-话术设置', NULL, 'botsentence_maker_setName', '13', 'botsentence_maker_setName', '0', '1', '2019-04-08 10:59:14', '1', '2019-04-08 10:59:14', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1015', '话术市场-行业模板-导入模板', NULL, 'botsentence_mytemplate_import', '15', 'botsentence_mytemplate_import', '0', '1', '2019-04-08 10:59:34', '1', '2019-04-08 10:59:34', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1016', '话术市场-话术制作-测试', NULL, 'botsentence_maker_test', '13', 'botsentence_maker_test', '0', '1', '2019-04-08 10:59:36', '1', '2019-04-08 10:59:36', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1017', '话术市场-行业模板-保存', NULL, 'botsentence_mytemplate_save', '15', 'botsentence_mytemplate_save', '0', '1', '2019-04-08 10:59:52', '1', '2019-04-08 10:59:52', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1018', '话术市场-话术制作-删除', NULL, 'botsentence_maker_delete', '13', 'botsentence_maker_delete', '0', '1', '2019-04-08 10:59:57', '1', '2019-04-08 10:59:57', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1019', '话术市场-话术制作-查看模板', NULL, 'botsentence_maker_look', '13', 'botsentence_maker_look', '0', '1', '2019-04-08 11:00:19', '1', '2019-04-08 11:00:19', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1020', '话术市场-话术审核-导出模板', NULL, 'botsentence_approve_export', '14', 'botsentence_approve_export', '0', '1', '2019-04-08 11:00:23', '1', '2019-04-08 11:00:23', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1021', '话术市场-话术审核-查看话术', NULL, 'botsentence_approve_look', '14', 'botsentence_approve_look', '0', '1', '2019-04-08 11:00:42', '1', '2019-04-08 11:00:42', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1023', '话术市场-模板市场-获取', NULL, 'botsentence_maker_market_get', '13', 'botsentence_maker_market_get', '0', '1', '2019-04-08 11:01:13', '1', '2019-04-08 11:01:13', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1024', '话术市场-话术制作-取消分享', NULL, 'botsentence_maker_cancelShare', '13', 'botsentence_maker_cancelShare', '0', '1', '2019-04-08 11:01:17', '1', '2019-04-08 11:01:17', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1028', '话术市场-模板市场-查看话术', NULL, 'botsentence_maker_market_look', '13', 'botsentence_maker_market_look', '0', '1', '2019-04-08 11:02:07', '1', '2019-04-08 11:02:07', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1029', '机器人中心-机器人实时配置-分配', NULL, 'robotCenter_simList_distribution', '134', 'robotCenter_simList_distribution', '0', '1', '2019-04-08 11:08:46', '1', '2019-04-08 11:08:46', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1030', '消息中心-站内信-删除', NULL, 'newsCenter_newsMail_delete', '130', 'newsCenter_newsMail_delete', '0', '1', '2019-04-08 11:09:41', '1', '2019-04-08 11:09:41', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1031', '消息中心-提醒设置-恢复默认', NULL, 'newsCenter_receiveSetting_reDefault', '131', 'newsCenter_receiveSetting_reDefault', '0', '1', '2019-04-08 11:11:12', '1', '2019-04-08 11:11:12', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1032', '消息中心-提醒设置-消息接收人', NULL, 'newsCenter_receiveSetting_editReceiver', '131', 'newsCenter_receiveSetting_editReceiver', '0', '1', '2019-04-08 11:11:36', '1', '2019-04-08 11:11:36', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1033', '消息中心-提醒设置-修改意向标签', NULL, 'newsCenter_receiveSetting_noticeType1', '131', 'newsCenter_receiveSetting_noticeType1', '0', '1', '2019-04-08 11:12:00', '1', '2019-04-08 11:12:00', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1034', '通信管理-线路市场-申请', NULL, 'comManage_application', '116', 'comManage_application', '0', '1', '2019-04-08 14:54:50', '1', '2019-04-08 14:54:50', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1035', '机器人中心-机器人配置-详情页增加', NULL, 'robotCenter_robotManage_detailAdd', '17', 'robotCenter_robotManage_detailAdd', '0', '1', '2019-04-08 14:57:11', '1', '2019-04-08 14:57:11', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1036', '机器人中心-机器人配置-详情删除', NULL, 'robotCenter_robotManage_detailDelete', '17', 'robotCenter_robotManage_detailDelete', '0', '1', '2019-04-08 14:57:41', '1', '2019-04-08 14:57:41', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1037', '通话记录-查询', NULL, 'callCenter_callHistory_defquery', '9', 'callCenter_callHistory_defquery', '0', '1', '2019-04-08 17:10:49', '1', '2019-04-08 17:10:49', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1038', '接待中心-查询', NULL, 'callCenter_workPlatform_defquery', '125', 'callCenter_workPlatform_defquery', '0', '1', '2019-04-08 17:11:31', '1', '2019-04-08 17:11:31', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1039', '登记历史-查询', NULL, 'callCenter_checklist_defquery', '126', 'callCenter_checklist_defquery', '0', '1', '2019-04-08 17:12:11', '1', '2019-04-08 17:12:11', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1040', '坐席组管理-查询', NULL, 'callCenter_agentGroupManage_defquery', '127', 'callCenter_agentGroupManage_defquery', '0', '1', '2019-04-08 17:12:38', '1', '2019-04-08 17:12:38', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1041', '坐席成员管理-查询', NULL, 'callCenter_agentStaffManage_defquery', '128', 'callCenter_agentStaffManage_defquery', '0', '1', '2019-04-08 17:13:03', '1', '2019-04-08 17:13:03', '2', '3', '0', '0', '0', NULL);
INSERT INTO temp_menu (`id`, `name`, `description`, `url`, `pid`, `permission`, `is_show`, `create_id`, `create_time`, `update_id`, `update_time`, `type`, `level`, `appid`, `remarks`, `del_flag`, `sys_type`) VALUES ('1042', '机器人配置-查询', NULL, 'robotCenter_robotManage_defquery', '17', 'robotCenter_robotManage_defquery', '0', '1', '2019-04-08 17:13:35', '1', '2019-04-08 17:13:35', '2', '3', '0', '0', '0', NULL);


INSERT INTO sys_menu (name, description, url, pid, permission, is_show, create_id, create_time, update_id, update_time, type, level, appid, remarks, del_flag, sys_type) select s2.name, s2.description, s2.url, s1.id, s2.permission, s2.is_show, s2.create_id, s2.create_time, s2.update_id, s2.update_time, s2.type, s2.level, s2.appid, s2.remarks, s2.del_flag, s2.sys_type from sys_menu s1,temp_menu s2 where s1.url=s2.purl;