server:
  port: 18012
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: guiyu-nas-web
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
  datasource:
    url: jdbc:mysql://192.168.1.81:3306/guiyu_base
    username: base
    password: base@1234
    driver-class-name: com.mysql.jdbc.Driver

  #数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/
#fastdfs配置
fdfs:
  soTimeout: 1500         #获取文件超时时间
  connectTimeout: 600     #连接超时时间
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.1.78:22122  #内网172.16.167.213
  pool:
    jmx-enabled: false
  webServerUrl: http://192.168.1.78:8080/
properties:
  error: properties/error.properties