server:
  port: 18004
spring:
  application:
    name: guiyu-callCenter-ccmanager2
  datasource:
    url: jdbc:mysql://47.97.179.12:3306/guiyu_callcenter?useUnicode=true&characterEncoding=utf-8
    username: root
    password: guiyu@1234
    driver-class-name: com.mysql.jdbc.Driver
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
  
#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://127.0.0.1:18081/eureka/