server:
  port: 18023
spring:
  application:
    name: guiyu-callCenter-ccmanager
  datasource:
  #内网
    #url: jdbc:mysql://172.16.167.215:3306/guiyu_callcenter?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://47.97.179.12:3306/guiyu_callcenter?useUnicode=true&characterEncoding=utf-8
    username: callcenter
    password: callcenter@1234
    driver-class-name: com.mysql.jdbc.Driver
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
  
#注册中心配置      
eureka:
  instance:
    #ip-address: 47.96.151.197
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://47.96.151.197:18001/eureka/
        #defaultZone: http://127.0.0.1:18001/eureka/
properties:
  error: error.properties