server:
  port: 18006

spring:
  application:
    name: guiyu-callcenter-fsagent

#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/

fs:
   #homeDir: /home/freeswitch/fs1
   homeDir: C:/Program Files/FreeSWITCH

job:
  clearRecord: 0 0 0 * * ?

path:
    recordPath: D:/record/
    tempPath: /home/aiwav/temp/
    ttsPath: /home/aiwav/tts/
    #tempPath: D:/aiwav/temp/
    tempRecordPath: /home/aiwav

properties:
    error: properties/error.properties


