server:
  port: 18006
  threadCount: 20

spring:
  application:
    name: guiyu-callcenter-fsagent
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/

fs:
   #homeDir: /home/freeswitch/fs1
   homeDir: C:/Program Files/FreeSWITCH

job:
  clearRecord: 0 0 0 * * ?

path:
    recordPath: D:/record/
    tempPath: /home/botstence_tmpl/
    ttsPath: /home/botstence_tmpl/tts/
    tempRecordPath: /home/aiwav

properties:
    error: properties/error.properties

rabbit:
  general:
    direct:
      queue: callCenter.record_update_mq


