server:
  port: 18051
spring:
  application:
    name: guiyu-ai-web
  datasource:
    url: jdbc:mysql://172.16.167.215:3311/guiyu_ai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true
    username: ai
    password: ai@1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 8
    host: 172.16.167.215
    password: Toolwiz.admin.2017
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
  rabbitmq:
    host: 172.16.167.215
    port: 5672
    virtual-host: /
    username: guiyu
    password: Guiyu.admin.2017
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
    
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/


#网关地址
gateway:
  host: http://guiyu-cloud-zuul:18000/
properties:
  error: properties/error.properties
  threadpool: properties/threadPool.properties
  

#xxl-job admin中心配置
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://172.16.167.213:18016/xxl-job-admin
    executor:
      ip: 172.16.167.213
      port: 9051
      logpath: /home/logs/guiyu-dispatch-web
      logretentiondays: -1
    accessToken:
ttsUrl: http://172.16.167.214:38002/ 
filePath: /home/apps/ai/wav/
notifyUrl: http://172.16.167.213:18000/ai/callback
