server:
  port: 18019
spring:
  application:
    name: guiyu-interface
#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
           defaultZone: http://192.168.1.78:18001/eureka/
jdbc:
  type: mysql