server:
  port: 19081
#myconfig
spring:
  application:
    name: guiyu-auth-web  
  datasource:  
    type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://localhost:3306/guiyu_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true
    username: root  
    password: 123456  
    driver-class-name: com.mysql.jdbc.Driver  
    minIdle: 1  
    maxActive: 2  
    initialSize: 1  
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 'ZTM' FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false    
    
mybatis:   
  mapperLocations: classpath*:mappers/*.xml  
  config-location: classpath:config/mybatis-config.xml      
#注册中心配置      
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    ##续约更新时间间隔设置5秒，m默认30s
#    lease-renewal-interval-in-seconds: 5
#    ##续约到期时间10秒，默认是90秒
#    lease-expiration-duration-in-seconds: 10
#  client:
#      service-url:
#        defaultZone: http://guiyu-cloud-registeration:18081/eureka/
#      instance:
#          status-page-url: http://localhost:18080/eureka//swagger-ui.html
##网关地址
#gateway:
#   host: http://guiyu-cloud-zuul:18080/
#
#ribbon:
#  ReadTimeout: 30000 #请求处理的超时时间
#  ConnectTimeout: 30000  #请求连接的超时时间
#  MaxAutoRetries: 0   #对当前实例的重试次数
#  MaxAutoRetriesNextServer: 1  #切换实例的重试次数
#  eureka:
#    enabled: true
#endpoints:
#  health:
#    sensitive: false
#    enabled: true
#management:
#  security:
#    enabled: false 

